Traceback (most recent call last):
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/gabrielsanchez/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import the required libraries
import pandas as pd
from fractions import Fraction

# Create a dictionary called 'g' that will be used to store global variables
g = globals()

# Set the plot style to 'ggplot' for consistent plot appearance
plt.style.use('ggplot')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 9>[0;34m()[0m
[1;32m      6[0m g [38;5;241m=[39m [38;5;28mglobals[39m()
[1;32m      8[0m [38;5;66;03m# Set the plot style to 'ggplot' for consistent plot appearance[39;00m
[0;32m----> 9[0m [43mplt[49m[38;5;241m.[39mstyle[38;5;241m.[39muse([38;5;124m'[39m[38;5;124mggplot[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

